package com.testproject.andrey.service;

import com.testproject.andrey.dto.HardDriveStatistics;

import java.text.DateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class castToDtoService {
    private static final DateTimeFormatter df = new DateTimeFormatter("yyyy-MM-dd");
    public HardDriveStatistics castToDto(String line) {
        int counter = 0;
        String[] strings = line.split(",");
        HardDriveStatistics statistics = new HardDriveStatistics().builder()
                .date(LocalDate.parse(strings[counter++], df))
                .serial_number(strings[counter++])
                .model(strings[counter++])
                .capacity_bytes(strings[counter++])
                .failure((strings[counter++]))
                .smart_1_normalized(strings[counter++])
                .smart_1_raw(strings[counter++])
                .smart_2_normalized(strings[counter++])
                .smart_2_raw(strings[counter++])
                .smart_3_normalized(strings[counter++])
                .smart_3_raw(strings[counter++])
                .smart_4_normalized(strings[counter++])
                .smart_4_raw(strings[counter++])
                .smart_5_normalized(strings[counter++])
                .smart_5_raw(strings[counter++])
                .smart_7_normalized(strings[counter++])
                .smart_7_raw(strings[counter++])
                .smart_8_normalized(strings[counter++])
                .smart_8_raw(strings[counter++])
                .smart_9_normalized(strings[counter++])
                .smart_9_raw(strings[counter++])
                .smart_10_normalized(strings[counter++])
                .smart_10_raw(strings[counter++])
                .smart_11_normalized(strings[counter++])
                .smart_11_raw(strings[counter++])
                .smart_12_normalized(strings[counter++])
                .smart_12_raw(strings[counter++])
                .smart_13_normalized(strings[counter++])
                .smart_13_raw(strings[counter++])
                .smart_15_normalized(strings[counter++])
                .smart_15_raw(strings[counter++])
                .smart_16_normalized(strings[counter++])
                .smart_16_raw(strings[counter++])
                .smart_17_normalized(strings[counter++])
                .smart_17_raw(strings[counter++])
                .smart_22_normalized(strings[counter++])
                .smart_22_raw(strings[counter++])
                .smart_23_normalized(strings[counter++])
                .smart_23_raw(strings[counter++])
                .smart_24_normalized(strings[counter++])
                .smart_24_raw(strings[counter++])
                .smart_168_normalized(strings[counter++])
                .smart_168_raw(strings[counter++])
                .smart_170_normalized(strings[counter++])
                .smart_170_raw(strings[counter++])
                .smart_173_normalized(strings[counter++])
                .smart_173_raw(strings[counter++])
                .smart_174_normalized(strings[counter++])
                .smart_174_raw(strings[counter++])
                .smart_177_normalized(strings[counter++])
                .smart_177_raw(strings[counter++])
                .smart_179_normalized(strings[counter++])
                .smart_179_raw(strings[counter++])
                .smart_181_normalized(strings[counter++])
                .smart_181_raw(strings[counter++])
                .smart_182_normalized(strings[counter++])
                .smart_182_raw(strings[counter++])
                .smart_183_normalized(strings[counter++])
                .smart_183_raw(strings[counter++])
                .smart_184_normalized(strings[counter++])
                .smart_184_raw(strings[counter++])
                .smart_187_normalized(strings[counter++])
                .smart_187_raw(strings[counter++])
                .smart_188_normalized(strings[counter++])
                .smart_188_raw(strings[counter++])
                .smart_189_normalized(strings[counter++])
                .smart_189_raw(strings[counter++])
                .smart_190_normalized(strings[counter++])
                .smart_190_raw(strings[counter++])
                .smart_191_normalized(strings[counter++])
                .smart_191_raw(strings[counter++])
                .smart_192_normalized(strings[counter++])
                .smart_192_raw(strings[counter++])
                .smart_193_normalized(strings[counter++])
                .smart_193_raw(strings[counter++])
                .smart_194_normalized(strings[counter++])
                .smart_194_raw(strings[counter++])
                .smart_195_normalized(strings[counter++])
                .smart_195_raw(strings[counter++])
                .smart_196_normalized(strings[counter++])
                .smart_196_raw(strings[counter++])
                .smart_197_normalized(strings[counter++])
                .smart_197_raw(strings[counter++])
                .smart_198_normalized(strings[counter++])
                .smart_198_raw(strings[counter++])
                .smart_199_normalized(strings[counter++])
                .smart_199_raw(strings[counter++])
                .smart_200_normalized(strings[counter++])
                .smart_200_raw(strings[counter++])
                .smart_201_normalized(strings[counter++])
                .smart_201_raw(strings[counter++])
                .smart_218_normalized(strings[counter++])
                .smart_218_raw(strings[counter++])
                .smart_220_normalized(strings[counter++])
                .smart_220_raw(strings[counter++])
                .smart_222_normalized(strings[counter++])
                .smart_222_raw(strings[counter++])
                .smart_223_normalized(strings[counter++])
                .smart_223_raw(strings[counter++])
                .smart_224_normalized(strings[counter++])
                .smart_224_raw(strings[counter++])
                .smart_225_normalized(strings[counter++])
                .smart_225_raw(strings[counter++])
                .smart_226_normalized(strings[counter++])
                .smart_226_raw(strings[counter++])
                .smart_231_normalized(strings[counter++])
                .smart_231_raw(strings[counter++])
                .smart_232_normalized(strings[counter++])
                .smart_232_raw(strings[counter++])
                .smart_233_normalized(strings[counter++])
                .smart_233_raw(strings[counter++])
                .smart_235_normalized(strings[counter++])
                .smart_235_raw(strings[counter++])
                .smart_240_normalized(strings[counter++])
                .smart_240_raw(strings[counter++])
                .smart_241_normalized(strings[counter++])
                .smart_241_raw(strings[counter++])
                .smart_242_normalized(strings[counter++])
                .smart_242_raw(strings[counter++])
                .smart_250_normalized(strings[counter++])
                .smart_250_raw(strings[counter++])
                .smart_251_normalized(strings[counter++])
                .smart_251_raw(strings[counter++])
                .smart_252_normalized(strings[counter++])
                .smart_252_raw(strings[counter++])
                .smart_254_normalized(strings[counter++])
                .smart_254_raw(strings[counter++])
                .smart_255_normalized(strings[counter++])
                .smart_255_raw(strings[counter])
                .build();
    }
}
